version: "3.8"
services: 
  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:4.4-debian-10
    ports: 
      - 27017:27017
    restart: always
    environment:
      MONGO_DATABASE: greenlight
    volumes: 
      - dblocal:/home/greenlight/mongo
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d/mongo-init.js

  
volumes:
  dblocal:
    driver: local