org: elioglima
app: aws-node-express-api-app
service: greenlight
provider:
  name: aws
  timeout: 30
  memorySize: 128
  runtime: nodejs14.x
  region: us-east-1 
  environment:
    MONGODB_URI: 'mongodb+srv://admin:AB102030@greenliht.z4jbtfo.mongodb.net/test'

functions: ${file(serverless/functions.yml)}

plugins:
  - serverless-offline

package:
  excludeDevDependencies: false